<?php

namespace App\Http\Resources;

use App\Support\Enums\IntentEnum;
use Illuminate\Http\Resources\Json\JsonResource;

class BupotResource extends JsonResource
{
    public function toArray($request): array
    {
        $intent = $request->get('intent');

        if ($request['jenis_spt_pph'] == 'L1') {
            $intent = IntentEnum::API_BUPOT_BPBPT->value;
        }else if ($request['jenis_spt_pph'] == 'L3') {
            $intent = IntentEnum::API_BUPOT_BP21->value;
            $intent = IntentEnum::API_BUPOT_BP26->value;
        }else if ($request['jenis_spt_pph'] == 'DAFTAR-1') {
            $intent = IntentEnum::API_BUPOT_BPPU->value;
            $intent = IntentEnum::API_BUPOT_BPNR->value;
        }else if ($request['jenis_spt_pph'] == 'DAFTAR-2') {
            $intent = IntentEnum::API_BUPOT_PS->value;
        }

        switch ($intent) {
            case IntentEnum::API_BUPOT_BPPU->value:
                return [
                    'id' => $this->id,
                    'created_at' => $this->created_at,
                    'updated_at' => $this->updated_at,
                    'tipe_bupot' => $this->tipe_bupot,
                    'masa_awal' => $this->masa_awal,
                    'nomor_pemotongan' => $this->nomor_pemotongan,
                    'status' => $this->status,
                    'status_penerbitan' => $this->status_penerbitan,
                    'bupot_tanda_tangan' => new BupotTandaTanganResource($this->penandatanganan),
                    // 'status_ttd_representatif' => $this->status_ttd_representatif,
                    'nitku' => $this->nitku,
                    'jenis_pajak' => $this->jenis_pajak,
                    'kode_objek_pajak' => $this->kode_objek_pajak,
                    'npwp_akun' => $this->npwp_akun,
                    'nama_akun' => $this->nama_akun,
                    'dasar_pengenaan_pajak' => $this->dasar_pengenaan_pajak,
                    'pajak_penghasilan' => $this->pajak_penghasilan,
                    'fasilitas_pajak' => $this->fasilitas_pajak,
                ];
            case IntentEnum::API_BUPOT_BPNR->value:
                return [
                    'id' => $this->id,
                    'created_at' => $this->created_at,
                    'updated_at' => $this->updated_at,
                    'tipe_bupot' => $this->tipe_bupot,
                    'masa_awal' => $this->masa_awal,
                    'nomor_pemotongan' => $this->nomor_pemotongan,
                    'status' => $this->status,
                    'status_penerbitan' => $this->status_penerbitan,
                    'bupot_tanda_tangan' => new BupotTandaTanganResource($this->penandatanganan),
                    // 'status_ttd_representatif' => $this->status_ttd_representatif,
                    'nitku' => $this->nitku,
                    'jenis_pajak' => $this->jenis_pajak,
                    'kode_objek_pajak' => $this->kode_objek_pajak,
                    'npwp_akun' => $this->npwp_akun,
                    'nama_akun' => $this->nama_akun,
                    'dasar_pengenaan_pajak' => $this->dasar_pengenaan_pajak,
                    'pajak_penghasilan' => $this->pajak_penghasilan,
                    'fasilitas_pajak' => $this->fasilitas_pajak,
                ];
            case IntentEnum::API_BUPOT_PS->value:
                return [
                    'id' => $this->id,
                    'created_at' => $this->created_at,
                    'updated_at' => $this->updated_at,
                    'tipe_bupot' => $this->tipe_bupot,
                    'masa_awal' => $this->masa_awal,
                    'nomor_pemotongan' => $this->nomor_pemotongan,
                    'status' => $this->status,
                    'status_penerbitan' => $this->status_penerbitan,
                    'bupot_tanda_tangan' => new BupotTandaTanganResource($this->penandatanganan),
                    // 'status_ttd_representatif' => $this->status_ttd_representatif,
                    'jenis_pajak' => $this->jenis_pajak,
                    'kode_objek_pajak' => $this->kode_objek_pajak,
                    'dasar_pengenaan_pajak' => $this->dasar_pengenaan_pajak,
                    'pajak_penghasilan' => $this->pajak_penghasilan,
                    'fasilitas_pajak' => $this->fasilitas_pajak,
                ];
            case IntentEnum::API_BUPOT_PSD->value:
                return [
                    'id' => $this->id,
                    'created_at' => $this->created_at,
                    'updated_at' => $this->updated_at,
                    'tipe_bupot' => $this->tipe_bupot,
                    'masa_awal' => $this->masa_awal,
                    'nomor_pemotongan' => $this->nomor_pemotongan,
                    'status' => $this->status,
                    'status_penerbitan' => $this->status_penerbitan,
                    'bupot_tanda_tangan' => new BupotTandaTanganResource($this->penandatanganan),
                    // 'status_ttd_representatif' => $this->status_ttd_representatif,
                    'jenis_pajak' => $this->jenis_pajak,
                    'kode_objek_pajak' => $this->kode_objek_pajak,
                    'dasar_pengenaan_pajak' => $this->dasar_pengenaan_pajak,
                    'pajak_penghasilan' => $this->pajak_penghasilan,
                    'fasilitas_pajak' => $this->fasilitas_pajak,
                ];
            case IntentEnum::API_BUPOT_BP21->value:
                return [
                    'id' => $this->id,
                    'created_at' => $this->created_at,
                    'updated_at' => $this->updated_at,
                    'tipe_bupot' => $this->tipe_bupot,
                    'masa_awal' => $this->masa_awal,
                    'nomor_pemotongan' => $this->nomor_pemotongan,
                    'status' => $this->status,
                    'status_penerbitan' => $this->status_penerbitan,
                    'bupot_tanda_tangan' => new BupotTandaTanganResource($this->penandatanganan),
                    // 'status_ttd_representatif' => $this->status_ttd_representatif,
                    'nitku' => $this->nitku,
                    'jenis_pajak' => $this->jenis_pajak,
                    'kode_objek_pajak' => $this->kode_objek_pajak,
                    'npwp_akun' => $this->npwp_akun,
                    'nama_akun' => $this->nama_akun,
                    'dasar_pengenaan_pajak' => $this->dasar_pengenaan_pajak,
                    'pajak_penghasilan' => $this->pajak_penghasilan,
                    'fasilitas_pajak' => $this->fasilitas_pajak,
                ];
            case IntentEnum::API_BUPOT_BP26->value:
                return [
                    'id' => $this->id,
                    'created_at' => $this->created_at,
                    'updated_at' => $this->updated_at,
                    'tipe_bupot' => $this->tipe_bupot,
                    'masa_awal' => $this->masa_awal,
                    'nomor_pemotongan' => $this->nomor_pemotongan,
                    'status' => $this->status,
                    'status_penerbitan' => $this->status_penerbitan,
                    'bupot_tanda_tangan' => new BupotTandaTanganResource($this->penandatanganan),
                    // 'status_ttd_representatif' => $this->status_ttd_representatif,
                    'nitku' => $this->nitku,
                    'jenis_pajak' => $this->jenis_pajak,
                    'kode_objek_pajak' => $this->kode_objek_pajak,
                    'npwp_akun' => $this->npwp_akun,
                    'nama_akun' => $this->nama_akun,
                    'dasar_pengenaan_pajak' => $this->dasar_pengenaan_pajak,
                    'pajak_penghasilan' => $this->pajak_penghasilan,
                    'fasilitas_pajak' => $this->fasilitas_pajak,
                ];
            case IntentEnum::API_BUPOT_BPA1->value:
                return [
                    'id' => $this->id,
                    'created_at' => $this->created_at,
                    'updated_at' => $this->updated_at,
                    'tipe_bupot' => $this->tipe_bupot,
                    'masa_awal' => $this->masa_awal,
                    'masa_akhir' => $this->masa_akhir,
                    'nomor_pemotongan' => $this->nomor_pemotongan,
                    'status' => $this->status,
                    'status_penerbitan' => $this->status_penerbitan,
                    'bupot_tanda_tangan' => new BupotTandaTanganResource($this->penandatanganan),
                    // 'status_ttd_representatif' => $this->status_ttd_representatif,
                    'nitku' => $this->nitku,
                    'jenis_pajak' => $this->jenis_pajak,
                    'kode_objek_pajak' => $this->kode_objek_pajak,
                    'npwp_akun' => $this->npwp_akun,
                    'nama_akun' => $this->nama_akun,
                    'dasar_pengenaan_pajak' => $this->dasar_pengenaan_pajak,
                    'pajak_penghasilan' => $this->pajak_penghasilan,
                    'penghasilan_kena_pajak' => $this->penghasilan_kena_pajak,
                    'fasilitas_pajak' => $this->fasilitas_pajak,
                ];
            case IntentEnum::API_BUPOT_BPA2->value:
                return [
                    'id' => $this->id,
                    'created_at' => $this->created_at,
                    'updated_at' => $this->updated_at,
                    'tipe_bupot' => $this->tipe_bupot,
                    'masa_awal' => $this->masa_awal,
                    'masa_akhir' => $this->masa_akhir,
                    'nomor_pemotongan' => $this->nomor_pemotongan,
                    'status' => $this->status,
                    'status_penerbitan' => $this->status_penerbitan,
                    'bupot_tanda_tangan' => new BupotTandaTanganResource($this->penandatanganan),
                    // 'status_ttd_representatif' => $this->status_ttd_representatif,
                    'nitku' => $this->nitku,
                    'jenis_pajak' => $this->jenis_pajak,
                    'kode_objek_pajak' => $this->kode_objek_pajak,
                    'npwp_akun' => $this->npwp_akun,
                    'nama_akun' => $this->nama_akun,
                    'dasar_pengenaan_pajak' => $this->dasar_pengenaan_pajak,
                    'pajak_penghasilan' => $this->pajak_penghasilan,
                    'penghasilan_kena_pajak' => $this->penghasilan_kena_pajak,
                ];
            case IntentEnum::API_BUPOT_BPBPT->value:
                return [
                    'id' => $this->id,
                    'created_at' => $this->created_at,
                    'updated_at' => $this->updated_at,
                    'tipe_bupot' => $this->tipe_bupot,
                    'masa_awal' => $this->masa_awal,
                    'nomor_pemotongan' => $this->nomor_pemotongan,
                    'status' => $this->status,
                    'status_penerbitan' => $this->status_penerbitan,
                    'bupot_tanda_tangan' => new BupotTandaTanganResource($this->penandatanganan),
                    // 'status_ttd_representatif' => $this->status_ttd_representatif,
                    'nitku' => $this->nitku,
                    'jenis_pajak' => $this->jenis_pajak,
                    'kode_objek_pajak' => $this->kode_objek_pajak,
                    'npwp_akun' => $this->npwp_akun,
                    'nama_akun' => $this->nama_akun,
                    'dasar_pengenaan_pajak' => $this->dasar_pengenaan_pajak,
                    'pajak_penghasilan' => $this->pajak_penghasilan,
                    'fasilitas_pajak' => $this->fasilitas_pajak,
                ];
            case IntentEnum::API_BUPOT_BPPU_SHOW->value:
                return [
                    'id' => $this->id,
                    'created_at' => $this->created_at->toDateTimeString(),
                    'updated_at' => $this->updated_at->toDateTimeString(),
                    'pembuat_id' => $this->pembuat_id,
                    'representatif_id' => $this->representatif_id,
                    'tipe_bupot' => $this->tipe_bupot,
                    'masa_awal' => $this->masa_awal,
                    'status' => $this->status,
                    'status_penerbitan' => $this->status_penerbitan,
                    'npwp_akun' => $this->npwp_akun,
                    'nama_akun' => $this->nama_akun,
                    'nitku' => $this->nitku,
                    'fasilitas_pajak' => $this->fasilitas_pajak,
                    'nama_objek_pajak' => $this->nama_objek_pajak,
                    'jenis_pajak' => $this->jenis_pajak,
                    'kode_objek_pajak' => $this->kode_objek_pajak,
                    'sifat_pajak_penghasilan' => $this->sifat_pajak_penghasilan,
                    'dasar_pengenaan_pajak' => $this->dasar_pengenaan_pajak,
                    'tarif_pajak' => $this->tarif_pajak,
                    'pajak_penghasilan' => $this->pajak_penghasilan,
                    'kap' => $this->kap,
                    'jenis_dokumen' => $this->jenis_dokumen,
                    'nomor_dokumen' => $this->nomor_dokumen,
                    'tanggal_dokumen' => $this->tanggal_dokumen,
                    'nitku_dokumen' => $this->nitku_dokumen,
                ];
            case IntentEnum::API_BUPOT_BPNR_SHOW->value:
                return [
                    'id' => $this->id,
                    'created_at' => $this->created_at->toDateTimeString(),
                    'updated_at' => $this->updated_at->toDateTimeString(),
                    'pembuat_id' => $this->pembuat_id,
                    'representatif_id' => $this->representatif_id,
                    'tipe_bupot' => $this->tipe_bupot,
                    'masa_awal' => $this->masa_awal,
                    'status' => $this->status,
                    'status_penerbitan' => $this->status_penerbitan,
                    'fasilitas_pajak' => $this->fasilitas_pajak,
                    'recipient_number' => $this->recipient_number,
                    'npwp_akun' => $this->npwp_akun,
                    'nama_akun' => $this->nama_akun,
                    'alamat_utama_akun' => $this->alamat_utama_akun,
                    'negara_akun' => $this->negara_akun,
                    'tanggal_lahir_akun' => $this->tanggal_lahir_akun,
                    'tempat_lahir_akun' => $this->tempat_lahir_akun,
                    'nomor_paspor_akun' => $this->nomor_paspor_akun,
                    'nomor_kitas_kitap_akun' => $this->nomor_kitas_kitap_akun,
                    'nama_objek_pajak' => $this->nama_objek_pajak,
                    'jenis_pajak' => $this->jenis_pajak,
                    'kode_objek_pajak' => $this->kode_objek_pajak,
                    'sifat_pajak_penghasilan' => $this->sifat_pajak_penghasilan,
                    'dasar_pengenaan_pajak' => $this->dasar_pengenaan_pajak,
                    'persentase_penghasilan_bersih' => $this->persentase_penghasilan_bersih,
                    'tarif_pajak' => $this->tarif_pajak,
                    'pajak_penghasilan' => $this->pajak_penghasilan,
                    'kap' => $this->kap,
                    'jenis_dokumen' => $this->jenis_dokumen,
                    'nomor_dokumen' => $this->nomor_dokumen,
                    'tanggal_dokumen' => $this->tanggal_dokumen,
                    'nitku_dokumen' => $this->nitku_dokumen,
                ];
            case IntentEnum::API_BUPOT_PS_SHOW->value:
                return [
                    'pembuat_id' => $this->pembuat_id,
                    'representatif_id' => $this->representatif_id,
                    'tipe_bupot' => $this->tipe_bupot,
                    'masa_awal' => $this->masa_awal,
                    'status' => $this->status,
                    'status_penerbitan' => $this->status_penerbitan,
                    'fasilitas_pajak' => $this->fasilitas_pajak,
                    'nama_objek_pajak' => $this->nama_objek_pajak,
                    'jenis_pajak' => $this->jenis_pajak,
                    'kode_objek_pajak' => $this->kode_objek_pajak,
                    'sifat_pajak_penghasilan' => $this->sifat_pajak_penghasilan,
                    'dasar_pengenaan_pajak' => $this->dasar_pengenaan_pajak,
                    'tarif_pajak' => $this->tarif_pajak,
                    'pajak_penghasilan' => $this->pajak_penghasilan,
                    'kap' => $this->kap,
                    'jenis_dokumen' => $this->jenis_dokumen,
                    'nomor_dokumen' => $this->nomor_dokumen,
                    'tanggal_dokumen' => $this->tanggal_dokumen,
                    'nitku_dokumen' => $this->nitku_dokumen,
                    'npwp_akun' => $this->npwp_akun,
                    'nama_akun' => $this->nama_akun,
                    'nitku' => $this->nitku,
                ];
            case IntentEnum::API_BUPOT_PSD_SHOW->value:
                return [
                    'pembuat_id' => $this->pembuat_id,
                    'representatif_id' => $this->representatif_id,
                    'tipe_bupot' => $this->tipe_bupot,
                    'masa_awal' => $this->masa_awal,
                    'status' => $this->status,
                    'status_penerbitan' => $this->status_penerbitan,
                    'fasilitas_pajak' => $this->fasilitas_pajak,
                    'nama_objek_pajak' => $this->nama_objek_pajak,
                    'jenis_pajak' => $this->jenis_pajak,
                    'kode_objek_pajak' => $this->kode_objek_pajak,
                    'sifat_pajak_penghasilan' => $this->sifat_pajak_penghasilan,
                    'dasar_pengenaan_pajak' => $this->dasar_pengenaan_pajak,
                    'tarif_pajak' => $this->tarif_pajak,
                    'pajak_penghasilan' => $this->pajak_penghasilan,
                    'kap' => $this->kap,
                    'jenis_dokumen' => $this->jenis_dokumen,
                    'nomor_dokumen' => $this->nomor_dokumen,
                    'tanggal_dokumen' => $this->tanggal_dokumen,
                    'nitku_dokumen' => $this->nitku_dokumen,
                    'npwp_akun' => $this->npwp_akun,
                    'nama_akun' => $this->nama_akun,
                    'nitku' => $this->nitku,
                ];
            case IntentEnum::API_BUPOT_BP21_SHOW->value:
                return [
                    'pembuat_id' => $this->pembuat_id,
                    'representatif_id' => $this->representatif_id,
                    'tipe_bupot' => $this->tipe_bupot,
                    'masa_awal' => $this->masa_awal,
                    'status' => $this->status,
                    'status_penerbitan' => $this->status_penerbitan,
                    'npwp_akun' => $this->npwp_akun,
                    'nama_akun' => $this->nama_akun,
                    'nitku' => $this->nitku,
                    'ptkp_akun' => $this->ptkp_akun,
                    'fasilitas_pajak' => $this->fasilitas_pajak,
                    'nama_objek_pajak' => $this->nama_objek_pajak,
                    'jenis_pajak' => $this->jenis_pajak,
                    'kode_objek_pajak' => $this->kode_objek_pajak,
                    'sifat_pajak_penghasilan' => $this->sifat_pajak_penghasilan,
                    'bruto_2_tahun' => $this->bruto_2_tahun,
                    'dasar_pengenaan_pajak' => $this->dasar_pengenaan_pajak,
                    'persentase_penghasilan_bersih' => $this->persentase_penghasilan_bersih,
                    'tarif_pajak' => $this->tarif_pajak,
                    'pajak_penghasilan' => $this->pajak_penghasilan,
                    'kap' => $this->kap,
                    'jenis_dokumen' => $this->jenis_dokumen,
                    'nomor_dokumen' => $this->nomor_dokumen,
                    'tanggal_dokumen' => $this->tanggal_dokumen,
                    'nitku_dokumen' => $this->nitku_dokumen,
                ];
            case IntentEnum::API_BUPOT_BP26_SHOW->value:
                return [
                    'pembuat_id' => $this->pembuat_id,
                    'representatif_id' => $this->representatif_id,
                    'tipe_bupot' => $this->tipe_bupot,
                    'masa_awal' => $this->masa_awal,
                    'status' => $this->status,
                    'status_penerbitan' => $this->status_penerbitan,
                    'fasilitas_pajak' => $this->fasilitas_pajak,
                    'npwp_akun' => $this->npwp_akun,
                    'nama_akun' => $this->nama_akun,
                    'alamat_utama_akun' => $this->alamat_utama_akun,
                    'negara_akun' => $this->negara_akun,
                    'tanggal_lahir_akun' => $this->tanggal_lahir_akun,
                    'tempat_lahir_akun' => $this->tempat_lahir_akun,
                    'nomor_paspor_akun' => $this->nomor_paspor_akun,
                    'nomor_kitas_kitap_akun' => $this->nomor_kitas_kitap_akun,
                    'nama_objek_pajak' => $this->nama_objek_pajak,
                    'jenis_pajak' => $this->jenis_pajak,
                    'kode_objek_pajak' => $this->kode_objek_pajak,
                    'sifat_pajak_penghasilan' => $this->sifat_pajak_penghasilan,
                    'dasar_pengenaan_pajak' => $this->dasar_pengenaan_pajak,
                    'persentase_penghasilan_bersih' => $this->persentase_penghasilan_bersih,
                    'tarif_pajak' => $this->tarif_pajak,
                    'pajak_penghasilan' => $this->pajak_penghasilan,
                    'kap' => $this->kap,
                    'jenis_dokumen' => $this->jenis_dokumen,
                    'nomor_dokumen' => $this->nomor_dokumen,
                    'tanggal_dokumen' => $this->tanggal_dokumen,
                    'nitku_dokumen' => $this->nitku_dokumen,
                ];
            case IntentEnum::API_BUPOT_BPA1_SHOW->value:
                return [
                    'pembuat_id' => $this->pembuat_id,
                    'representatif_id' => $this->representatif_id,
                    'tipe_bupot' => $this->tipe_bupot,
                    'bekerja_di_lebih_dari_satu_pemberi_kerja' => $this->bekerja_di_lebih_dari_satu_pemberi_kerja,
                    'masa_awal' => $this->masa_awal,
                    'masa_akhir' => $this->masa_akhir,
                    'status' => $this->status,
                    'status_penerbitan' => $this->status_penerbitan,
                    'pegawai_asing' => $this->pegawai_asing,
                    'npwp_akun' => $this->npwp_akun,
                    'nama_akun' => $this->nama_akun,
                    'alamat_utama_akun' => $this->alamat_utama_akun,
                    'nomor_paspor_akun' => $this->nomor_paspor_akun,
                    'negara_akun' => $this->negara_akun,
                    'jenis_kelamin_akun' => $this->jenis_kelamin_akun,
                    'ptkp_akun' => $this->ptkp_akun,
                    'posisi_akun' => $this->posisi_akun,
                    'nama_objek_pajak' => $this->nama_objek_pajak,
                    'jenis_pajak' => $this->jenis_pajak,
                    'kode_objek_pajak' => $this->kode_objek_pajak,
                    'jenis_pemotongan' => $this->jenis_pemotongan,
                    'gaji_pokok_pensiun' => $this->gaji_pokok_pensiun,
                    'pembulatan_kotor' => $this->pembulatan_kotor,
                    'tunjangan_pph' => $this->tunjangan_pph,
                    'tunjangan_lainnya' => $this->tunjangan_lainnya,
                    'honorarium_imbalan_lainnya' => $this->honorarium_imbalan_lainnya,
                    'premi_asuransi_pemberi_kerja' => $this->premi_asuransi_pemberi_kerja,
                    'natura_pph_pasal_21' => $this->natura_pph_pasal_21,
                    'tantiem_bonus_gratifikasi_jasa_thr' => $this->tantiem_bonus_gratifikasi_jasa_thr,
                    'dasar_pengenaan_pajak' => $this->dasar_pengenaan_pajak,
                    'biaya_jabatan' => $this->biaya_jabatan,
                    'iuran_pensiun' => $this->iuran_pensiun,
                    'sumbangan_keagamaan_pemberi_kerja' => $this->sumbangan_keagamaan_pemberi_kerja,
                    'jumlah_pengurangan' => $this->jumlah_pengurangan,
                    'jumlah_penghasilan_neto' => $this->jumlah_penghasilan_neto,
                    'nomor_bpa1_sebelumnya' => $this->nomor_bpa1_sebelumnya,
                    'penghasilan_neto_sebelumnya' => $this->penghasilan_neto_sebelumnya,
                    'penghasilan_neto_pph_pasal_21' => $this->penghasilan_neto_pph_pasal_21,
                    'penghasilan_tidak_kena_pajak' => $this->penghasilan_tidak_kena_pajak,
                    'penghasilan_kena_pajak' => $this->penghasilan_kena_pajak,
                    'pph_pasal_21_penghasilan_kena_pajak' => $this->pph_pasal_21_penghasilan_kena_pajak,
                    'pph_pasal_21_terutang' => $this->pph_pasal_21_terutang,
                    'pph_pasal_21_potongan_bpa1_sebelumnya' => $this->pph_pasal_21_potongan_bpa1_sebelumnya,
                    'pph_pasal_21_terutang_bupot_ini' => $this->pph_pasal_21_terutang_bupot_ini,
                    'pph_pasal_21_ditanggung_pemerintah' => $this->pph_pasal_21_ditanggung_pemerintah,
                    'pph_pasal_21_masa_pajak_terakhir' => $this->pph_pasal_21_masa_pajak_terakhir,
                    'fasilitas_pajak' => $this->fasilitas_pajak,
                    'kap' => $this->kap,
                    'nitku' => $this->nitku,
                ];
            case IntentEnum::API_BUPOT_BPA2_SHOW->value:
                return [
                    'pembuat_id' => $this->pembuat_id,
                    'representatif_id' => $this->representatif_id,
                    'tipe_bupot' => $this->tipe_bupot,
                    'bekerja_di_lebih_dari_satu_pemberi_kerja' => $this->bekerja_di_lebih_dari_satu_pemberi_kerja,
                    'masa_awal' => $this->masa_awal,
                    'masa_akhir' => $this->masa_akhir,
                    'status' => $this->status,
                    'status_penerbitan' => $this->status_penerbitan,
                    'npwp_akun' => $this->npwp_akun,
                    'nama_akun' => $this->nama_akun,
                    'alamat_utama_akun' => $this->alamat_utama_akun,
                    'nip_akun' => $this->nip_akun,
                    'jenis_kelamin_akun' => $this->jenis_kelamin_akun,
                    'pangkat_golongan_akun' => $this->pangkat_golongan_akun,
                    'ptkp_akun' => $this->ptkp_akun,
                    'posisi_akun' => $this->posisi_akun,
                    'nama_objek_pajak' => $this->nama_objek_pajak,
                    'jenis_pajak' => $this->jenis_pajak,
                    'kode_objek_pajak' => $this->kode_objek_pajak,
                    'jenis_pemotongan' => $this->jenis_pemotongan,
                    'gaji_pokok_pensiun' => $this->gaji_pokok_pensiun,
                    'tunjangan_istri' => $this->tunjangan_istri,
                    'tunjangan_anak' => $this->tunjangan_anak,
                    'tunjangan_perbaikan_penghasilan' => $this->tunjangan_perbaikan_penghasilan,
                    'tunjangan_struktural_fungsional' => $this->tunjangan_struktural_fungsional,
                    'tunjangan_beras' => $this->tunjangan_beras,
                    'tunjangan_lainnya' => $this->tunjangan_lainnya,
                    'penghasilan_tetap_lainnya' => $this->penghasilan_tetap_lainnya,
                    'biaya_jabatan' => $this->biaya_jabatan,
                    'iuran_pensiun' => $this->iuran_pensiun,
                    'sumbangan_keagamaan_pemberi_kerja' => $this->sumbangan_keagamaan_pemberi_kerja,
                    'jumlah_pengurangan' => $this->jumlah_pengurangan,
                    'jumlah_penghasilan_neto' => $this->jumlah_penghasilan_neto,
                    'nomor_bpa1_sebelumnya' => $this->nomor_bpa1_sebelumnya,
                    'penghasilan_neto_sebelumnya' => $this->penghasilan_neto_sebelumnya,
                    'penghasilan_neto_pph_pasal_21' => $this->penghasilan_neto_pph_pasal_21,
                    'penghasilan_tidak_kena_pajak' => $this->penghasilan_tidak_kena_pajak,
                    'penghasilan_kena_pajak' => $this->penghasilan_kena_pajak,
                    'pph_pasal_21_penghasilan_kena_pajak' => $this->pph_pasal_21_penghasilan_kena_pajak,
                    'pph_pasal_21_terutang' => $this->pph_pasal_21_terutang,
                    'pph_pasal_21_potongan_bpa1_sebelumnya' => $this->pph_pasal_21_potongan_bpa1_sebelumnya,
                    'pph_pasal_21_terutang_bupot_ini' => $this->pph_pasal_21_terutang_bupot_ini,
                    'pph_pasal_21_ditanggung_pemerintah' => $this->pph_pasal_21_ditanggung_pemerintah,
                    'pph_pasal_21_masa_pajak_terakhir' => $this->pph_pasal_21_masa_pajak_terakhir,
                    'kap' => $this->kap,
                    'nitku' => $this->nitku,
                ];
            case IntentEnum::API_BUPOT_BPBPT_SHOW->value:
                return [
                    'pembuat_id' => $this->pembuat_id,
                    'representatif_id' => $this->representatif_id,
                    'tipe_bupot' => $this->tipe_bupot,
                    'masa_awal' => $this->masa_awal,
                    'status' => $this->status,
                    'status_penerbitan' => $this->status_penerbitan,
                    'pegawai_asing' => $this->pegawai_asing,
                    'npwp_akun' => $this->npwp_akun,
                    'nama_akun' => $this->nama_akun,
                    'alamat_utama_akun' => $this->alamat_utama_akun,
                    'nomor_paspor_akun' => $this->nomor_paspor_akun,
                    'negara_akun' => $this->negara_akun,
                    'ptkp_akun' => $this->ptkp_akun,
                    'posisi_akun' => $this->posisi_akun,
                    'fasilitas_pajak' => $this->fasilitas_pajak,
                    'nama_objek_pajak' => $this->nama_objek_pajak,
                    'jenis_pajak' => $this->jenis_pajak,
                    'kode_objek_pajak' => $this->kode_objek_pajak,
                    'dasar_pengenaan_pajak' => $this->dasar_pengenaan_pajak,
                    'tarif_pajak' => $this->tarif_pajak,
                    'pajak_penghasilan' => $this->pajak_penghasilan,
                    'kap' => $this->kap,
                    'nitku' => $this->nitku,
                ];
            // case IntentEnum::API_BUPOT_DSBP->value:
            //     return [
            //         'id' => $this->id,
            //         'created_at' => $this->created_at->toDateTimeString(),
            //         'updated_at' => $this->updated_at->toDateTimeString(),
            //     ];
        }

        return [
            'id' => $this->id,
            'created_at' => $this->created_at->toDateTimeString(),
            'updated_at' => $this->updated_at->toDateTimeString(),
        ];
    }
}
