<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class SptPpnResource extends JsonResource {
    public function toArray($request): array {
        return [
            'id' => $this->id,
            'pic_id' => $this->pic_id,
            'periode' => $this->periode,
            'klasifikasi_lapangan_usaha' => $this->klasifikasi_lapangan_usaha,
            'is_pembetulan' => $this->is_pembetulan,
            'cl_1a1_dpp' => $this->cl_1a1_dpp,
            'cl_1a2_dpp' => $this->cl_1a2_dpp,
            'cl_1a3_dpp' => $this->cl_1a3_dpp,
            'cl_1a4_dpp' => $this->cl_1a4_dpp,
            'cl_1a5_dpp' => $this->cl_1a5_dpp,
            'cl_1a6_dpp' => $this->cl_1a6_dpp,
            'cl_1a7_dpp' => $this->cl_1a7_dpp,
            'cl_1a8_dpp' => $this->cl_1a8_dpp,
            'cl_1a9_dpp' => $this->cl_1a9_dpp,
            'cl_1a_jumlah_dpp' => $this->cl_1a_jumlah_dpp,
            'cl_1b_dpp' => $this->cl_1b_dpp,
            'cl_1c_dpp' => $this->cl_1c_dpp,
            'cl_1a2_dpp_lain' => $this->cl_1a2_dpp_lain,
            'cl_1a3_dpp_lain' => $this->cl_1a3_dpp_lain,
            'cl_1a5_dpp_lain' => $this->cl_1a5_dpp_lain,
            'cl_1a6_dpp_lain' => $this->cl_1a6_dpp_lain,
            'cl_1a7_dpp_lain' => $this->cl_1a7_dpp_lain,
            'cl_1a8_dpp_lain' => $this->cl_1a8_dpp_lain,
            'cl_1a9_dpp_lain' => $this->cl_1a9_dpp_lain,
            'cl_1a2_ppn' => $this->cl_1a2_ppn,
            'cl_1a4_ppn' => $this->cl_1a4_ppn,
            'cl_1a3_ppn' => $this->cl_1a3_ppn,
            'cl_1a5_ppn' => $this->cl_1a5_ppn,
            'cl_1a6_ppn' => $this->cl_1a6_ppn,
            'cl_1a7_ppn' => $this->cl_1a7_ppn,
            'cl_1a8_ppn' => $this->cl_1a8_ppn,
            'cl_1a9_ppn' => $this->cl_1a9_ppn,
            'cl_1a_jumlah_ppn' => $this->cl_1a_jumlah_ppn,
            'cl_1a2_ppnbm' => $this->cl_1a2_ppnbm,
            'cl_1a4_ppnbm' => $this->cl_1a4_ppnbm,
            'cl_1a3_ppnbm' => $this->cl_1a3_ppnbm,
            'cl_1a5_ppnbm' => $this->cl_1a5_ppnbm,
            'cl_1a6_ppnbm' => $this->cl_1a6_ppnbm,
            'cl_1a7_ppnbm' => $this->cl_1a7_ppnbm,
            'cl_1a8_ppnbm' => $this->cl_1a8_ppnbm,
            'cl_1a9_ppnbm' => $this->cl_1a9_ppnbm,
            'cl_1a_jumlah_ppnbm' => $this->cl_1a_jumlah_ppnbm,
            'cl_2a_dpp' => $this->cl_2a_dpp,
            'cl_2b_dpp_lain' => $this->cl_2b_dpp_lain,
            'cl_2b_dpp' => $this->cl_2b_dpp,
            'cl_2c_dpp' => $this->cl_2c_dpp,
            'cl_2d_dpp_lain' => $this->cl_2d_dpp_lain,
            'cl_2a_ppnbm' => $this->cl_2a_ppnbm,
            'cl_2b_ppnbm' => $this->cl_2b_ppnbm,
            'cl_2c_ppnbm' => $this->cl_2c_ppnbm,
            'cl_2d_ppnbm' => $this->cl_2d_ppnbm,
            'cl_2d_dpp' => $this->cl_2d_dpp,
            'cl_2g_dpp' => $this->cl_2g_dpp,
            'cl_2h_dpp_lain' => $this->cl_2h_dpp_lain,
            'cl_2a_ppn' => $this->cl_2a_ppn,
            'cl_2b_ppn' => $this->cl_2b_ppn,
            'cl_2c_ppn' => $this->cl_2c_ppn,
            'cl_2d_ppn' => $this->cl_2d_ppn,
            'cl_2e_ppn' => $this->cl_2e_ppn,
            'cl_2f_ppn' => $this->cl_2f_ppn,
            'cl_2g_ppn' => $this->cl_2g_ppn,
            'cl_2h_ppn' => $this->cl_2h_ppn,
            'cl_2h_dpp' => $this->cl_2h_dpp,
            'cl_2h_ppnbm' => $this->cl_2h_ppnbm,
            'cl_2i_dpp' => $this->cl_2i_dpp,
            'cl_2j_dpp' => $this->cl_2j_dpp,
            'cl_3a_ppn' => $this->cl_3a_ppn,
            'cl_3b_ppn' => $this->cl_3b_ppn,
            'cl_3c_ppn' => $this->cl_3c_ppn,
            'cl_3d_ppn' => $this->cl_3d_ppn,
            'cl_3e_ppn' => $this->cl_3e_ppn,
            'cl_3f_ppn' => $this->cl_3f_ppn,
            'cl_3g_ppn' => $this->cl_3g_ppn,
            'cl_3h_diminta' => $this->cl_3h_diminta,
            'cl_3h_nomor_rekening' => $this->cl_3_nomor_rekening,
            'cl_3h_nama_bank' => $this->cl_3_nama_bank,
            'cl_3h_nama_pemilik_rekening' => $this->cl_3_nama_pemilik_rekening,
            'cl_4_ppn_terutang_dpp' => $this->cl_4_ppn_terutang_dpp,
            'cl_4_ppn_terutang' => $this->cl_4_ppn_terutang,
            'cl_5_ppn_wajib' => $this->cl_5_ppn_wajib,
            'cl_6a_ppnbm' => $this->cl_6a_ppnbm,
            'cl_6b_ppnbm' => $this->cl_6b_ppnbm,
            'cl_6c_ppnbm' => $this->cl_6c_ppnbm,
            'cl_6d_ppnbm' => $this->cl_6d_ppnbm,
            'cl_6e_ppnbm' => $this->cl_6e_ppnbm,
            'cl_6f_diminta_pengembalian' => $this->cl_6f_diminta_pengembalian,
            'cl_7a_ppnbm' => $this->cl_7a_ppnbm,
            'cl_7b_ppnbm' => $this->cl_7b_ppnbm,
            'cl_7c_ppnbm' => $this->cl_7c_ppnbm,
            'cl_7a_ppn' => $this->cl_7a_ppn,
            'cl_7b_ppn' => $this->cl_7b_ppn,
            'cl_7c_ppn' => $this->cl_7c_ppn,
            'cl_7a_dpp_lain' => $this->cl_7a_dpp_lain,
            'cl_7b_dpp_lain' => $this->cl_7b_dpp_lain,
            'cl_7c_dpp_lain' => $this->cl_7c_dpp_lain,
            'cl_7a_dpp' => $this->cl_7a_dpp,
            'cl_7b_dpp' => $this->cl_7b_dpp,
            'cl_7c_dpp' => $this->cl_7c_dpp,
            'cl_8a_ppnbm' => $this->cl_8a_ppnbm,
            'cl_8b_ppnbm' => $this->cl_8b_ppnbm,
            'cl_8c_ppnbm' => $this->cl_8c_ppnbm,
            'cl_8a_ppn' => $this->cl_8a_ppn,
            'cl_8b_ppn' => $this->cl_8b_ppn,
            'cl_8c_ppn' => $this->cl_8c_ppn,
            'cl_8a_dpp_lain' => $this->cl_8a_dpp_lain,
            'cl_8b_dpp_lain' => $this->cl_8b_dpp_lain,
            'cl_8c_dpp_lain' => $this->cl_8c_dpp_lain,
            'cl_8a_dpp' => $this->cl_8a_dpp,
            'cl_8b_dpp' => $this->cl_8b_dpp,
            'cl_8c_dpp' => $this->cl_8c_dpp,
            'cl_8d_diminta_pengembalian' => $this->cl_8d_diminta_pengembalian,
            'cl_9a_daftar' => $this->cl_9a_daftar,
            'cl_9b_hasil_perhitungan' => $this->cl_9b_hasil_perhitungan,
            'cl_10_batas_waktu' => $this->cl_10_batas_waktu,
            'created_at' => $this->created_at->toDateTimeString(),
            'updated_at' => $this->updated_at->toDateTimeString(),
        ];
    }
}
