<?php

namespace App\Http\Resources;

use App\Support\Enums\IntentEnum;
use Illuminate\Http\Resources\Json\JsonResource;

class SptPpnResource extends JsonResource {
    public function toArray($request): array {
        $intent = $request->get('intent');

        return [
            'id' => $this->id,
            'klasifikasi_lapangan_usaha' => $this->klasifikasi_lapangan_usaha ?? 0,
            'cl_1a1_dpp' => $this->cl_1a1_dpp ?? 0,
            'cl_1a2_dpp' => $this->cl_1a2_dpp ?? 0,
            'cl_1a3_dpp' => $this->cl_1a3_dpp ?? 0,
            'cl_1a4_dpp' => $this->cl_1a4_dpp ?? 0,
            'cl_1a5_dpp' => $this->cl_1a5_dpp ?? 0,
            'cl_1a6_dpp' => $this->cl_1a6_dpp ?? 0,
            'cl_1a7_dpp' => $this->cl_1a7_dpp ?? 0,
            'cl_1a8_dpp' => $this->cl_1a8_dpp ?? 0,
            'cl_1a9_dpp' => $this->cl_1a9_dpp ?? 0,
            'cl_1a_jumlah_dpp' => $this->cl_1a_jumlah_dpp ?? 0,
            'cl_1b_jumlah_dpp' => $this->cl_1b_jumlah_dpp ?? 0,
            'cl_1c_jumlah_dpp' => $this->cl_1c_jumlah_dpp ?? 0,
            'cl_1a2_dpp_lain' => $this->cl_1a2_dpp_lain ?? 0,
            'cl_1a3_dpp_lain' => $this->cl_1a3_dpp_lain ?? 0,
            'cl_1a5_dpp_lain' => $this->cl_1a5_dpp_lain ?? 0,
            'cl_1a6_dpp_lain' => $this->cl_1a6_dpp_lain ?? 0,
            'cl_1a7_dpp_lain' => $this->cl_1a7_dpp_lain ?? 0,
            'cl_1a8_dpp_lain' => $this->cl_1a8_dpp_lain ?? 0,
            'cl_1a9_dpp_lain' => $this->cl_1a9_dpp_lain ?? 0,
            'cl_1a2_ppn' => $this->cl_1a2_ppn ?? 0,
            'cl_1a4_ppn' => $this->cl_1a4_ppn ?? 0,
            'cl_1a3_ppn' => $this->cl_1a3_ppn ?? 0,
            'cl_1a5_ppn' => $this->cl_1a5_ppn ?? 0,
            'cl_1a6_ppn' => $this->cl_1a6_ppn ?? 0,
            'cl_1a7_ppn' => $this->cl_1a7_ppn ?? 0,
            'cl_1a8_ppn' => $this->cl_1a8_ppn ?? 0,
            'cl_1a9_ppn' => $this->cl_1a9_ppn ?? 0,
            'cl_1a_jumlah_ppn' => $this->cl_1a_jumlah_ppn ?? 0,
            'cl_1a2_ppnbm' => $this->cl_1a2_ppnbm ?? 0,
            'cl_1a4_ppnbm' => $this->cl_1a4_ppnbm ?? 0,
            'cl_1a3_ppnbm' => $this->cl_1a3_ppnbm ?? 0,
            'cl_1a5_ppnbm' => $this->cl_1a5_ppnbm ?? 0,
            'cl_1a6_ppnbm' => $this->cl_1a6_ppnbm ?? 0,
            'cl_1a7_ppnbm' => $this->cl_1a7_ppnbm ?? 0,
            'cl_1a8_ppnbm' => $this->cl_1a8_ppnbm ?? 0,
            'cl_1a9_ppnbm' => $this->cl_1a9_ppnbm ?? 0,
            'cl_1a_jumlah_ppnbm' => $this->cl_1a_jumlah_ppnbm ?? 0,
            'cl_2a_dpp' => $this->cl_2a_dpp ?? 0,
            'cl_2b_dpp_lain' => $this->cl_2b_dpp_lain ?? 0,
            'cl_2b_dpp' => $this->cl_2b_dpp ?? 0,
            'cl_2c_dpp' => $this->cl_2c_dpp ?? 0,
            'cl_2d_dpp_lain' => $this->cl_2d_dpp_lain ?? 0,
            'cl_2a_ppnbm' => $this->cl_2a_ppnbm ?? 0,
            'cl_2b_ppnbm' => $this->cl_2b_ppnbm ?? 0,
            'cl_2c_ppnbm' => $this->cl_2c_ppnbm ?? 0,
            'cl_2d_ppnbm' => $this->cl_2d_ppnbm ?? 0,
            'cl_2d_dpp' => $this->cl_2d_dpp ?? 0,
            'cl_2g_dpp' => $this->cl_2g_dpp ?? 0,
            'cl_2h_dpp_lain' => $this->cl_2h_dpp_lain ?? 0,
            'cl_2a_ppn' => $this->cl_2a_ppn ?? 0,
            'cl_2b_ppn' => $this->cl_2b_ppn ?? 0,
            'cl_2c_ppn' => $this->cl_2c_ppn ?? 0,
            'cl_2d_ppn' => $this->cl_2d_ppn ?? 0,
            'cl_2e_ppn' => $this->cl_2e_ppn ?? 0,
            'cl_2f_ppn' => $this->cl_2f_ppn ?? 0,
            'cl_2g_ppn' => $this->cl_2g_ppn ?? 0,
            'cl_2h_ppn' => $this->cl_2h_ppn ?? 0,
            'cl_2h_dpp' => $this->cl_2h_dpp ?? 0,
            'cl_2h_ppnbm' => $this->cl_2h_ppnbm ?? 0,
            'cl_2i_dpp' => $this->cl_2i_dpp ?? 0,
            'cl_2j_dpp' => $this->cl_2j_dpp ?? 0,
            'cl_3a_ppn' => $this->cl_3a_ppn ?? 0,
            'cl_3b_ppn' => $this->cl_3b_ppn ?? 0,
            'cl_3c_ppn' => $this->cl_3c_ppn ?? 0,
            'cl_3d_ppn' => $this->cl_3d_ppn ?? 0,
            'cl_3e_ppn' => $this->cl_3e_ppn ?? 0,
            'cl_3f_ppn' => $this->cl_3f_ppn ?? 0,
            'cl_3g_ppn' => $this->cl_3g_ppn ?? 0,
            'cl_3h_diminta' => $this->cl_3h_diminta ?? 0,
            'cl_3h_nomor_rekening' => $this->cl_3_nomor_rekening ?? 0,
            'cl_3h_nama_bank' => $this->cl_3_nama_bank ?? 0,
            'cl_3h_nama_pemilik_rekening' => $this->cl_3_nama_pemilik_rekening ?? 0,
            'cl_4_ppn_terutang_dpp' => $this->cl_4_ppn_terutang_dpp ?? 0,
            'cl_4_ppn_terutang' => $this->cl_4_ppn_terutang ?? 0,
            'cl_5_ppn_wajib' => $this->cl_5_ppn_wajib ?? 0,
            'cl_6a_ppnbm' => $this->cl_6a_ppnbm ?? 0,
            'cl_6b_ppnbm' => $this->cl_6b_ppnbm ?? 0,
            'cl_6c_ppnbm' => $this->cl_6c_ppnbm ?? 0,
            'cl_6d_ppnbm' => $this->cl_6d_ppnbm ?? 0,
            'cl_6e_ppnbm' => $this->cl_6e_ppnbm ?? 0,
            'cl_6f_diminta_pengembalian' => $this->cl_6f_diminta_pengembalian ?? 0,
            'cl_7a_ppnbm' => $this->cl_7a_ppnbm ?? 0,
            'cl_7b_ppnbm' => $this->cl_7b_ppnbm ?? 0,
            'cl_7c_ppnbm' => $this->cl_7c_ppnbm ?? 0,
            'cl_7a_ppn' => $this->cl_7a_ppn ?? 0,
            'cl_7b_ppn' => $this->cl_7b_ppn ?? 0,
            'cl_7c_ppn' => $this->cl_7c_ppn ?? 0,
            'cl_7a_dpp_lain' => $this->cl_7a_dpp_lain ?? 0,
            'cl_7b_dpp_lain' => $this->cl_7b_dpp_lain ?? 0,
            'cl_7c_dpp_lain' => $this->cl_7c_dpp_lain ?? 0,
            'cl_7a_dpp' => $this->cl_7a_dpp ?? 0,
            'cl_7b_dpp' => $this->cl_7b_dpp ?? 0,
            'cl_7c_dpp' => $this->cl_7c_dpp ?? 0,
            'cl_8a_ppnbm' => $this->cl_8a_ppnbm ?? 0,
            'cl_8b_ppnbm' => $this->cl_8b_ppnbm ?? 0,
            'cl_8c_ppnbm' => $this->cl_8c_ppnbm ?? 0,
            'cl_8a_ppn' => $this->cl_8a_ppn ?? 0,
            'cl_8b_ppn' => $this->cl_8b_ppn ?? 0,
            'cl_8c_ppn' => $this->cl_8c_ppn ?? 0,
            'cl_8a_dpp_lain' => $this->cl_8a_dpp_lain ?? 0,
            'cl_8b_dpp_lain' => $this->cl_8b_dpp_lain ?? 0,
            'cl_8c_dpp_lain' => $this->cl_8c_dpp_lain ?? 0,
            'cl_8a_dpp' => $this->cl_8a_dpp ?? 0,
            'cl_8b_dpp' => $this->cl_8b_dpp ?? 0,
            'cl_8c_dpp' => $this->cl_8c_dpp ?? 0,
            'cl_8d_diminta_pengembalian' => $this->cl_8d_diminta_pengembalian ?? 0,
            'cl_9a_daftar' => $this->cl_9a_daftar ?? 0,
            'cl_9b_hasil_perhitungan' => $this->cl_9b_hasil_perhitungan ?? 0,
            'cl_10_batas_waktu' => $this->cl_10_batas_waktu ?? 0,
            'created_at' => $this->created_at->toDateTimeString(),
            'updated_at' => $this->updated_at->toDateTimeString(),
        ];
    }
}
