<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class SptUnifikasiResource extends JsonResource {
    public function toArray($request): array {
        return [
            'id' => $this->id,
            'cl_total_setor' => $this->cl_total_setor ?? 0,
            'cl_total_potong' => $this->cl_total_potong ?? 0,
            'cl_total_tanggung' => $this->cl_total_tanggung ?? 0,
            'cl_total_bayar'=> $this->cl_total_bayar ?? 0,
            'cl_total_betul'=> $this->cl_total_betul ?? 0,
            'cl_a_pasal26' => $this->cl_a_pasal26 ?? 0,
            'cl_a_pasal23' => $this->cl_a_pasal23 ?? 0,
            'cl_a_pasal22' => $this->cl_a_pasal22 ?? 0,
            'cl_a_pasal15' => $this->cl_a_pasal15 ?? 0,
            'cl_a_pasal4' => $this->cl_a_pasal4 ?? 0,
            'cl_a_1' => $this->cl_a_1 ?? 0,
            'cl_a_2' => $this->cl_a_2 ?? 0,
            'cl_a_3' => $this->cl_a_3 ?? 0,
            'cl_a_4' => $this->cl_a_4 ?? 0,
            'cl_a_5' => $this->cl_a_5 ?? 0,
            'cl_a_6' => $this->cl_a_6 ?? 0,
            'cl_a_7' => $this->cl_a_7 ?? 0,
            'cl_a_8' => $this->cl_a_8 ?? 0,
            'cl_a_9' => $this->cl_a_9 ?? 0,
            'cl_a_10' => $this->cl_a_10 ?? 0,
            'cl_b_pasal26' => $this->cl_b_pasal26 ?? 0,
            'cl_b_pasal23' => $this->cl_b_pasal23 ?? 0,
            'cl_b_pasal22' => $this->cl_b_pasal22 ?? 0,
            'cl_b_pasal15' => $this->cl_b_pasal15 ?? 0,
            'cl_b_pasal4' => $this->cl_b_pasal4 ?? 0,
            'cl_b_1' => $this->cl_b_1 ?? 0,
            'cl_b_2' => $this->cl_b_2 ?? 0,
            'cl_b_3' => $this->cl_b_3 ?? 0,
            'cl_b_4' => $this->cl_b_4 ?? 0,
            'cl_b_5' => $this->cl_b_5 ?? 0,
            'cl_b_6' => $this->cl_b_6 ?? 0,
            'cl_b_7' => $this->cl_b_7 ?? 0,
            'cl_b_8' => $this->cl_b_8 ?? 0,
            'cl_b_9' => $this->cl_b_9 ?? 0,
            'cl_b_10' => $this->cl_b_10 ?? 0,
            'cl_c_pasal26' => $this->cl_c_pasal26 ?? 0,
            'cl_c_pasal23' => $this->cl_c_pasal23 ?? 0,
            'cl_c_pasal22' => $this->cl_c_pasal22 ?? 0,
            'cl_c_pasal15' => $this->cl_c_pasal15 ?? 0,
            'cl_c_pasal4' => $this->cl_c_pasal4 ?? 0,
            'cl_c_1' => $this->cl_c_1 ?? 0,
            'cl_c_2' => $this->cl_c_2 ?? 0,
            'cl_c_3' => $this->cl_c_3 ?? 0,
            'cl_c_4' => $this->cl_c_4 ?? 0,
            'cl_c_5' => $this->cl_c_5 ?? 0,
            'cl_c_6' => $this->cl_c_6 ?? 0,
            'cl_c_7' => $this->cl_c_7 ?? 0,
            'cl_c_8' => $this->cl_c_8 ?? 0,
            'cl_c_9' => $this->cl_c_9 ?? 0,
            'cl_c_10' => $this->cl_c_10 ?? 0,
            'cl_d_pasal26' => $this->cl_d_pasal26 ?? 0,
            'cl_d_pasal23' => $this->cl_d_pasal23 ?? 0,
            'cl_d_pasal22' => $this->cl_d_pasal22 ?? 0,
            'cl_d_pasal15' => $this->cl_d_pasal15 ?? 0,
            'cl_d_pasal4' => $this->cl_d_pasal4 ?? 0,
            'cl_d_1' => $this->cl_d_1 ?? 0,
            'cl_d_2' => $this->cl_d_2 ?? 0,
            'cl_d_3' => $this->cl_d_3 ?? 0,
            'cl_d_4' => $this->cl_d_4 ?? 0,
            'cl_d_5' => $this->cl_d_5 ?? 0,
            'cl_d_6' => $this->cl_d_6 ?? 0,
            'cl_d_7' => $this->cl_d_7 ?? 0,
            'cl_d_8' => $this->cl_d_8 ?? 0,
            'cl_d_9' => $this->cl_d_9 ?? 0,
            'cl_d_10' => $this->cl_d_10 ?? 0,
            'cl_e_pasal26' => $this->cl_e_pasal26 ?? 0,
            'cl_e_pasal23' => $this->cl_e_pasal23 ?? 0,
            'cl_e_pasal22' => $this->cl_e_pasal22 ?? 0,
            'cl_e_pasal15' => $this->cl_e_pasal15 ?? 0,
            'cl_e_pasal4' => $this->cl_e_pasal4 ?? 0,
            'cl_e_1' => $this->cl_e_1 ?? 0,
            'cl_e_2' => $this->cl_e_2 ?? 0,
            'cl_e_3' => $this->cl_e_3 ?? 0,
            'cl_e_4' => $this->cl_e_4 ?? 0,
            'cl_e_5' => $this->cl_e_5 ?? 0,
            'cl_e_6' => $this->cl_e_6 ?? 0,
            'cl_e_7' => $this->cl_e_7 ?? 0,
            'cl_e_8' => $this->cl_e_8 ?? 0,
            'cl_e_9' => $this->cl_e_9 ?? 0,
            'cl_e_10' => $this->cl_e_10 ?? 0,
            'created_at' => $this->created_at->toDateTimeString(),
            'updated_at' => $this->updated_at->toDateTimeString(),
        ];
    }
}
