<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class SptUnifikasiResource extends JsonResource {
    public function toArray($request): array {
        return [
            'id' => $this->id,
            'cl_total_setor' => $this->cl_total_setor,
            'cl_total_potong' => $this->cl_total_potong,
            'cl_total_tanggung' => $this->cl_total_tanggung,
            'cl_total_bayar'=> $this->cl_total_bayar,
            'cl_total_betul'=> $this->cl_total_betul,
            'cl_a_pasal26' => $this->cl_a_pasal26,
            'cl_a_pasal23' => $this->cl_a_pasal23,
            'cl_a_pasal22' => $this->cl_a_pasal22,
            'cl_a_pasal15' => $this->cl_a_pasal15,
            'cl_a_pasal4' => $this->cl_a_pasal4,
            'cl_a_1' => $this->cl_a_1,
            'cl_a_2' => $this->cl_a_2,
            'cl_a_3' => $this->cl_a_3,
            'cl_a_4' => $this->cl_a_4,
            'cl_a_5' => $this->cl_a_5,
            'cl_a_6' => $this->cl_a_6,
            'cl_a_7' => $this->cl_a_7,
            'cl_a_8' => $this->cl_a_8,
            'cl_a_9' => $this->cl_a_9,
            'cl_a_10' => $this->cl_a_10,
            'cl_b_pasal26' => $this->cl_b_pasal26,
            'cl_b_pasal23' => $this->cl_b_pasal23,
            'cl_b_pasal22' => $this->cl_b_pasal22,
            'cl_b_pasal15' => $this->cl_b_pasal15,
            'cl_b_pasal4' => $this->cl_b_pasal4,
            'cl_b_1' => $this->cl_b_1,
            'cl_b_2' => $this->cl_b_2,
            'cl_b_3' => $this->cl_b_3,
            'cl_b_4' => $this->cl_b_4,
            'cl_b_5' => $this->cl_b_5,
            'cl_b_6' => $this->cl_b_6,
            'cl_b_7' => $this->cl_b_7,
            'cl_b_8' => $this->cl_b_8,
            'cl_b_9' => $this->cl_b_9,
            'cl_b_10' => $this->cl_b_10,
            'cl_c_pasal26' => $this->cl_c_pasal26,
            'cl_c_pasal23' => $this->cl_c_pasal23,
            'cl_c_pasal22' => $this->cl_c_pasal22,
            'cl_c_pasal15' => $this->cl_c_pasal15,
            'cl_c_pasal4' => $this->cl_c_pasal4,
            'cl_c_1' => $this->cl_c_1,
            'cl_c_2' => $this->cl_c_2,
            'cl_c_3' => $this->cl_c_3,
            'cl_c_4' => $this->cl_c_4,
            'cl_c_5' => $this->cl_c_5,
            'cl_c_6' => $this->cl_c_6,
            'cl_c_7' => $this->cl_c_7,
            'cl_c_8' => $this->cl_c_8,
            'cl_c_9' => $this->cl_c_9,
            'cl_c_10' => $this->cl_c_10,
            'cl_d_pasal26' => $this->cl_d_pasal26,
            'cl_d_pasal23' => $this->cl_d_pasal23,
            'cl_d_pasal22' => $this->cl_d_pasal22,
            'cl_d_pasal15' => $this->cl_d_pasal15,
            'cl_d_pasal4' => $this->cl_d_pasal4,
            'cl_d_1' => $this->cl_d_1,
            'cl_d_2' => $this->cl_d_2,
            'cl_d_3' => $this->cl_d_3,
            'cl_d_4' => $this->cl_d_4,
            'cl_d_5' => $this->cl_d_5,
            'cl_d_6' => $this->cl_d_6,
            'cl_d_7' => $this->cl_d_7,
            'cl_d_8' => $this->cl_d_8,
            'cl_d_9' => $this->cl_d_9,
            'cl_d_10' => $this->cl_d_10,
            'cl_e_pasal26' => $this->cl_e_pasal26,
            'cl_e_pasal23' => $this->cl_e_pasal23,
            'cl_e_pasal22' => $this->cl_e_pasal22,
            'cl_e_pasal15' => $this->cl_e_pasal15,
            'cl_e_pasal4' => $this->cl_e_pasal4,
            'cl_e_1' => $this->cl_e_1,
            'cl_e_2' => $this->cl_e_2,
            'cl_e_3' => $this->cl_e_3,
            'cl_e_4' => $this->cl_e_4,
            'cl_e_5' => $this->cl_e_5,
            'cl_e_6' => $this->cl_e_6,
            'cl_e_7' => $this->cl_e_7,
            'cl_e_8' => $this->cl_e_8,
            'cl_e_9' => $this->cl_e_9,
            'cl_e_10' => $this->cl_e_10,
            'created_at' => $this->created_at->toDateTimeString(),
            'updated_at' => $this->updated_at->toDateTimeString(),
        ];
    }
}
