<?php

namespace App\Http\Requests\Bupot;

use App\Support\Enums\PTKPEnum;
use App\Support\Enums\GenderEnum;
use App\Support\Enums\IntentEnum;
use App\Support\Enums\BupotTypeEnum;
use App\Support\Enums\BupotDokumenTypeEnum;
use Illuminate\Foundation\Http\FormRequest;

class UpdateBupotRequest extends FormRequest {
    public function rules(): array {
        $intent = $this->get('intent');
        switch ($intent) {
            case IntentEnum::API_BUPOT_BPPU->value:
                return [
                    'pembuat_id' => 'nullable|exists:sistems,id',
                    'representatif_id' => 'nullable|exists:sistems,id',
                    'tipe_bupot' => 'nullable|in:' . implode(',', BupotTypeEnum::toArray()),
                    'masa_awal' => 'nullable|date',
                    'status' => 'nullable|in:' . implode(',', ['valid', 'invalid', 'normal', 'pembetulan', 'dihapus', 'pembatalan']),
                    'status_penerbitan' => 'nullable|in:' . implode(',', ['draft', 'published', 'invalid']),
                    'npwp_akun' => 'nullable|string|max:255',
                    'nama_akun' => 'nullable|string|max:255',
                    'nitku' => 'nullable|string|max:255',
                    'fasilitas_pajak' => 'nullable|string|max:255',
                    'nama_objek_pajak' => 'nullable|string',
                    'jenis_pajak' => 'nullable|string|max:255',
                    'kode_objek_pajak' => 'nullable|string|max:255',
                    'sifat_pajak_penghasilan' => 'nullable|string|max:255',
                    'dasar_pengenaan_pajak' => 'nullable|numeric|min:0',
                    'tarif_pajak' => 'nullable|numeric|min:0',
                    'pajak_penghasilan' => 'nullable|numeric|min:0',
                    'kap' => 'nullable|string|max:255',
                    'jenis_dokumen' => 'nullable|in:' . implode(',', BupotDokumenTypeEnum::toArray()),
                    'nomor_dokumen' => 'nullable|string|max:255',
                    'tanggal_dokumen' => 'nullable|date',
                    'nitku_dokumen' => 'nullable|string|max:255',
                ];
            case IntentEnum::API_BUPOT_BPNR->value:
                return [
                    'pembuat_id' => 'nullable|exists:sistems,id',
                    'representatif_id' => 'nullable|exists:sistems,id',
                    'tipe_bupot' => 'nullable|in:' . implode(',', BupotTypeEnum::toArray()),
                    'masa_awal' => 'nullable|date',
                    'status' => 'nullable|in:' . implode(',', ['valid', 'invalid', 'normal', 'pembetulan', 'dihapus', 'pembatalan']),
                    'status_penerbitan' => 'nullable|in:' . implode(',', ['draft', 'published', 'invalid']),
                    'fasilitas_pajak' => 'nullable|string|max:255',
                    'npwp_akun' => 'nullable|string|max:255',
                    'nama_akun' => 'nullable|string|max:255',
                    'alamat_utama_akun' => 'nullable|string|max:255',
                    'negara_akun' => 'nullable|string|max:255',
                    'tanggal_lahir_akun' => 'nullable|date',
                    'tempat_lahir_akun' => 'nullable|string|max:255',
                    'nomor_paspor_akun' => 'nullable|string|max:255',
                    'nomor_kitas_kitap_akun' => 'nullable|string|max:255',
                    'nama_objek_pajak' => 'nullable|string',
                    'jenis_pajak' => 'nullable|string|max:255',
                    'kode_objek_pajak' => 'nullable|string|max:255',
                    'sifat_pajak_penghasilan' => 'nullable|string|max:255',
                    'dasar_pengenaan_pajak' => 'nullable|numeric|min:0',
                    'persentase_penghasilan_bersih' => 'nullable|numeric|min:0',
                    'tarif_pajak' => 'nullable|numeric|min:0',
                    'pajak_penghasilan' => 'nullable|numeric|min:0',
                    'kap' => 'nullable|string|max:255',
                    'jenis_dokumen' => 'nullable|in:' . implode(',', BupotDokumenTypeEnum::toArray()),
                    'nomor_dokumen' => 'nullable|string|max:255',
                    'tanggal_dokumen' => 'nullable|date',
                    'nitku_dokumen' => 'nullable|string|max:255',
                ];
            case IntentEnum::API_BUPOT_PS->value:
                return [
                    'pembuat_id' => 'nullable|exists:sistems,id',
                    'representatif_id' => 'nullable|exists:sistems,id',
                    'tipe_bupot' => 'nullable|in:' . implode(',', BupotTypeEnum::toArray()),
                    'masa_awal' => 'nullable|date',
                    'status' => 'nullable|in:' . implode(',', ['valid', 'invalid', 'normal', 'pembetulan', 'dihapus', 'pembatalan']),
                    'status_penerbitan' => 'nullable|in:' . implode(',', ['draft', 'published', 'invalid']),
                    'fasilitas_pajak' => 'nullable|string|max:255',
                    'nama_objek_pajak' => 'nullable|string',
                    'jenis_pajak' => 'nullable|string|max:255',
                    'kode_objek_pajak' => 'nullable|string|max:255',
                    'sifat_pajak_penghasilan' => 'nullable|string|max:255',
                    'dasar_pengenaan_pajak' => 'nullable|numeric|min:0',
                    'tarif_pajak' => 'nullable|numeric|min:0',
                    'pajak_penghasilan' => 'nullable|numeric|min:0',
                    'kap' => 'nullable|string|max:255',
                    'jenis_dokumen' => 'nullable|in:' . implode(',', BupotDokumenTypeEnum::toArray()),
                    'nomor_dokumen' => 'nullable|string|max:255',
                    'tanggal_dokumen' => 'nullable|date',
                    'nitku_dokumen' => 'nullable|string|max:255',
                    // NAMA, NPWP, NITKU AKUN ada di SERVICE BUPOT PS
                ];
            case IntentEnum::API_BUPOT_PSD->value:
                return [
                    'pembuat_id' => 'nullable|exists:sistems,id',
                    'representatif_id' => 'nullable|exists:sistems,id',
                    'tipe_bupot' => 'nullable|in:' . implode(',', BupotTypeEnum::toArray()),
                    'masa_awal' => 'nullable|date',
                    'status' => 'nullable|in:' . implode(',', ['valid', 'invalid', 'normal', 'pembetulan', 'dihapus', 'pembatalan']),
                    'status_penerbitan' => 'nullable|in:' . implode(',', ['draft', 'published', 'invalid']),
                    'fasilitas_pajak' => 'nullable|string|max:255',
                    'nama_objek_pajak' => 'nullable|string',
                    'jenis_pajak' => 'nullable|string|max:255',
                    'kode_objek_pajak' => 'nullable|string|max:255',
                    'sifat_pajak_penghasilan' => 'nullable|string|max:255',
                    'dasar_pengenaan_pajak' => 'nullable|numeric|min:0',
                    'tarif_pajak' => 'nullable|numeric|min:0',
                    'pajak_penghasilan' => 'nullable|numeric|min:0',
                    'kap' => 'nullable|string|max:255',
                    'jenis_dokumen' => 'nullable|in:' . implode(',', BupotDokumenTypeEnum::toArray()),
                    'nomor_dokumen' => 'nullable|string|max:255',
                    'tanggal_dokumen' => 'nullable|date',
                    'nitku_dokumen' => 'nullable|string|max:255',
                    // NAMA, NPWP, NITKU AKUN ada di SERVICE BUPOT PSD
                ];
            case IntentEnum::API_BUPOT_BP21->value:
                return [
                    'pembuat_id' => 'nullable|exists:sistems,id',
                    'representatif_id' => 'nullable|exists:sistems,id',
                    'tipe_bupot' => 'nullable|in:' . implode(',', BupotTypeEnum::toArray()),
                    'masa_awal' => 'nullable|date',
                    'status' => 'nullable|in:' . implode(',', ['valid', 'invalid', 'normal', 'pembetulan', 'dihapus', 'pembatalan']),
                    'status_penerbitan' => 'nullable|in:' . implode(',', ['draft', 'published', 'invalid']),
                    'npwp_akun' => 'nullable|string|max:255',
                    'nama_akun' => 'nullable|string|max:255',
                    'nitku' => 'nullable|string|max:255',
                    'ptkp_akun' => 'nullable|in:' . implode(',', PTKPEnum::toArray()),
                    'fasilitas_pajak' => 'nullable|string|max:255',
                    'nama_objek_pajak' => 'nullable|string',
                    'jenis_pajak' => 'nullable|string|max:255',
                    'kode_objek_pajak' => 'nullable|string|max:255',
                    'sifat_pajak_penghasilan' => 'nullable|string|max:255',
                    'bruto_2_tahun' => 'nullable|numeric|min:0',
                    'dasar_pengenaan_pajak' => 'nullable|numeric|min:0',
                    'persentase_penghasilan_bersih' => 'nullable|numeric|min:0',
                    'tarif_pajak' => 'nullable|numeric|min:0',
                    'pajak_penghasilan' => 'nullable|numeric|min:0',
                    'kap' => 'nullable|string|max:255',
                    'jenis_dokumen' => 'nullable|in:' . implode(',', BupotDokumenTypeEnum::toArray()),
                    'nomor_dokumen' => 'nullable|string|max:255',
                    'tanggal_dokumen' => 'nullable|date',
                    'nitku_dokumen' => 'nullable|string|max:255',
                ];
            case IntentEnum::API_BUPOT_BP26->value:
                return [
                    'pembuat_id' => 'nullable|exists:sistems,id',
                    'representatif_id' => 'nullable|exists:sistems,id',
                    'tipe_bupot' => 'nullable|in:' . implode(',', BupotTypeEnum::toArray()),
                    'masa_awal' => 'nullable|date',
                    'status' => 'nullable|in:' . implode(',', ['valid', 'invalid', 'normal', 'pembetulan', 'dihapus', 'pembatalan']),
                    'status_penerbitan' => 'nullable|in:' . implode(',', ['draft', 'published', 'invalid']),
                    'fasilitas_pajak' => 'nullable|string|max:255',
                    'npwp_akun' => 'nullable|string|max:255',
                    'nama_akun' => 'nullable|string|max:255',
                    'alamat_utama_akun' => 'nullable|string|max:255',
                    'negara_akun' => 'nullable|string|max:255',
                    'tanggal_lahir_akun' => 'nullable|date',
                    'tempat_lahir_akun' => 'nullable|string|max:255',
                    'nomor_paspor_akun' => 'nullable|string|max:255',
                    'nomor_kitas_kitap_akun' => 'nullable|string|max:255',
                    'nama_objek_pajak' => 'nullable|string',
                    'jenis_pajak' => 'nullable|string|max:255',
                    'kode_objek_pajak' => 'nullable|string|max:255',
                    'sifat_pajak_penghasilan' => 'nullable|string|max:255',
                    'dasar_pengenaan_pajak' => 'nullable|numeric|min:0',
                    'persentase_penghasilan_bersih' => 'nullable|numeric|min:0',
                    'tarif_pajak' => 'nullable|numeric|min:0',
                    'pajak_penghasilan' => 'nullable|numeric|min:0',
                    'kap' => 'nullable|string|max:255',
                    'jenis_dokumen' => 'nullable|in:' . implode(',', BupotDokumenTypeEnum::toArray()),
                    'nomor_dokumen' => 'nullable|string|max:255',
                    'tanggal_dokumen' => 'nullable|date',
                    'nitku_dokumen' => 'nullable|string|max:255',
                ];
            case IntentEnum::API_BUPOT_BPA1->value:
                return [
                    'pembuat_id' => 'nullable|exists:sistems,id',
                    'representatif_id' => 'nullable|exists:sistems,id',
                    'tipe_bupot' => 'nullable|in:' . implode(',', BupotTypeEnum::toArray()),
                    'bekerja_di_lebih_dari_satu_pemberi_kerja' => 'nullable|boolean',
                    'masa_awal' => 'nullable|date',
                    'masa_akhir' => 'nullable|date',
                    'status' => 'nullable|in:' . implode(',', ['valid', 'invalid', 'normal', 'pembetulan', 'dihapus', 'pembatalan']),
                    'status_penerbitan' => 'nullable|in:' . implode(',', ['draft', 'published', 'invalid']),
                    'pegawai_asing' => 'nullable|boolean',
                    'npwp_akun' => 'nullable|string|max:255',
                    'nama_akun' => 'nullable|string|max:255',
                    'alamat_utama_akun' => 'nullable|string|max:255',
                    'nomor_paspor_akun' => 'nullable|string|max:255',
                    'negara_akun' => 'nullable|string|max:255',
                    'jenis_kelamin_akun' => 'nullable|in:' . implode(',', GenderEnum::toArray()),
                    'ptkp_akun' => 'nullable|in:' . implode(',', PTKPEnum::toArray()),
                    'posisi_akun' => 'nullable|string|max:255',
                    'nama_objek_pajak' => 'nullable|string',
                    'jenis_pajak' => 'nullable|string|max:255',
                    'kode_objek_pajak' => 'nullable|string|max:255',
                    'jenis_pemotongan' => 'nullable|string|max:255',
                    'gaji_pokok_pensiun' => 'nullable|numeric|min:0',
                    'pembulatan_kotor' => 'nullable|numeric|min:0',
                    'tunjangan_pph' => 'nullable|numeric|min:0',
                    'tunjangan_lainnya' => 'nullable|numeric|min:0',
                    'honorarium_imbalan_lainnya' => 'nullable|numeric|min:0',
                    'premi_asuransi_pemberi_kerja' => 'nullable|numeric|min:0',
                    'natura_pph_pasal_21' => 'nullable|numeric|min:0',
                    'tantiem_bonus_gratifikasi_jasa_thr' => 'nullable|numeric|min:0',
                    'dasar_pengenaan_pajak' => 'nullable|numeric|min:0',
                    'biaya_jabatan' => 'nullable|numeric|min:0',
                    'iuran_pensiun' => 'nullable|numeric|min:0',
                    'sumbangan_keagamaan_pemberi_kerja' => 'nullable|numeric|min:0',
                    'jumlah_pengurangan' => 'nullable|numeric|min:0',
                    'jumlah_penghasilan_neto' => 'nullable|numeric|min:0',
                    'nomor_bpa1_sebelumnya' => 'nullable|numeric|min:0',
                    'penghasilan_neto_sebelumnya' => 'nullable|numeric|min:0',
                    'penghasilan_neto_pph_pasal_21' => 'nullable|numeric|min:0',
                    'penghasilan_tidak_kena_pajak' => 'nullable|numeric|min:0',
                    'penghasilan_kena_pajak' => 'nullable|numeric|min:0',
                    'pph_pasal_21_penghasilan_kena_pajak' => 'nullable|numeric|min:0',
                    'pph_pasal_21_terutang' => 'nullable|numeric|min:0',
                    'pph_pasal_21_potongan_bpa1_sebelumnya' => 'nullable|numeric|min:0',
                    'pph_pasal_21_terutang_bupot_ini' => 'nullable|numeric|min:0',
                    'pph_pasal_21_ditanggung_pemerintah' => 'nullable|numeric|min:0',
                    'pph_pasal_21_masa_pajak_terakhir' => 'nullable|numeric|min:0',
                    'fasilitas_pajak' => 'nullable|string|max:255',
                    'kap' => 'nullable|string|max:255',
                    'nitku' => 'nullable|string|max:255',
                ];
            case IntentEnum::API_BUPOT_BPA2->value:
                return [
                    'pembuat_id' => 'nullable|exists:sistems,id',
                    'representatif_id' => 'nullable|exists:sistems,id',
                    'tipe_bupot' => 'nullable|in:' . implode(',', BupotTypeEnum::toArray()),
                    'bekerja_di_lebih_dari_satu_pemberi_kerja' => 'nullable|boolean',
                    'masa_awal' => 'nullable|date',
                    'masa_akhir' => 'nullable|date',
                    'status' => 'nullable|in:' . implode(',', ['valid', 'invalid', 'normal', 'pembetulan', 'dihapus', 'pembatalan']),
                    'status_penerbitan' => 'nullable|in:' . implode(',', ['draft', 'published', 'invalid']),
                    'npwp_akun' => 'nullable|string|max:255',
                    'nama_akun' => 'nullable|string|max:255',
                    'alamat_utama_akun' => 'nullable|string|max:255',
                    'nip_akun' => 'nullable|string|max:255',
                    'jenis_kelamin_akun' => 'nullable|in:' . implode(',', GenderEnum::toArray()),
                    'pangkat_golongan_akun' => 'nullable|string|max:255',
                    'ptkp_akun' => 'nullable|in:' . implode(',', PTKPEnum::toArray()),
                    'posisi_akun' => 'nullable|string|max:255',
                    'nama_objek_pajak' => 'nullable|string',
                    'jenis_pajak' => 'nullable|string|max:255',
                    'kode_objek_pajak' => 'nullable|string|max:255',
                    'jenis_pemotongan' => 'nullable|string|max:255',
                    'gaji_pokok_pensiun' => 'nullable|numeric|min:0',
                    'tunjangan_istri' => 'nullable|numeric|min:0',
                    'tunjangan_anak' => 'nullable|numeric|min:0',
                    'tunjangan_perbaikan_penghasilan' => 'nullable|numeric|min:0',
                    'tunjangan_struktural_fungsional' => 'nullable|numeric|min:0',
                    'tunjangan_beras' => 'nullable|numeric|min:0',
                    'tunjangan_lainnya' => 'nullable|numeric|min:0',
                    'penghasilan_tetap_lainnya' => 'nullable|numeric|min:0',
                    'biaya_jabatan' => 'nullable|numeric|min:0',
                    'iuran_pensiun' => 'nullable|numeric|min:0',
                    'sumbangan_keagamaan_pemberi_kerja' => 'nullable|numeric|min:0',
                    'jumlah_pengurangan' => 'nullable|numeric|min:0',
                    'jumlah_penghasilan_neto' => 'nullable|numeric|min:0',
                    'nomor_bpa1_sebelumnya' => 'nullable|numeric|min:0',
                    'penghasilan_neto_sebelumnya' => 'nullable|numeric|min:0',
                    'penghasilan_neto_pph_pasal_21' => 'nullable|numeric|min:0',
                    'penghasilan_tidak_kena_pajak' => 'nullable|numeric|min:0',
                    'penghasilan_kena_pajak' => 'nullable|numeric|min:0',
                    'pph_pasal_21_penghasilan_kena_pajak' => 'nullable|numeric|min:0',
                    'pph_pasal_21_terutang' => 'nullable|numeric|min:0',
                    'pph_pasal_21_potongan_bpa1_sebelumnya' => 'nullable|numeric|min:0',
                    'pph_pasal_21_terutang_bupot_ini' => 'nullable|numeric|min:0',
                    'pph_pasal_21_ditanggung_pemerintah' => 'nullable|numeric|min:0',
                    'pph_pasal_21_masa_pajak_terakhir' => 'nullable|numeric|min:0',
                    'kap' => 'nullable|string|max:255',
                    'nitku' => 'nullable|string|max:255',
                ];
            case IntentEnum::API_BUPOT_BPBPT->value:
                return [
                    'pembuat_id' => 'nullable|exists:sistems,id',
                    'representatif_id' => 'nullable|exists:sistems,id',
                    'tipe_bupot' => 'nullable|in:' . implode(',', BupotTypeEnum::toArray()),
                    'masa_awal' => 'nullable|date',
                    'status' => 'nullable|in:' . implode(',', ['valid', 'invalid', 'normal', 'pembetulan', 'dihapus', 'pembatalan']),
                    'status_penerbitan' => 'nullable|in:' . implode(',', ['draft', 'published', 'invalid']),
                    'pegawai_asing' => 'nullable|boolean',
                    'npwp_akun' => 'nullable|string|max:255',
                    'nama_akun' => 'nullable|string|max:255',
                    'alamat_utama_akun' => 'nullable|string|max:255',
                    'nomor_paspor_akun' => 'nullable|string|max:255',
                    'negara_akun' => 'nullable|string|max:255',
                    'ptkp_akun' => 'nullable|in:' . implode(',', PTKPEnum::toArray()),
                    'posisi_akun' => 'nullable|string|max:255',
                    'fasilitas_pajak' => 'nullable|string|max:255',
                    'nama_objek_pajak' => 'nullable|string',
                    'jenis_pajak' => 'nullable|string|max:255',
                    'kode_objek_pajak' => 'nullable|string|max:255',
                    'dasar_pengenaan_pajak' => 'nullable|numeric|min:0',
                    'tarif_pajak' => 'nullable|numeric|min:0',
                    'pajak_penghasilan' => 'nullable|numeric|min:0',
                    'kap' => 'nullable|string|max:255',
                    'nitku' => 'nullable|string|max:255',
                ];
            // case IntentEnum::API_BUPOT_DSBP->value:
            //     return [
            //         'pembuat_id' => 'nullable|exists:sistems,id',
            //         'representatif_id' => 'nullable|exists:sistems,id',
            //         'tipe_bupot' => 'nullable|in:' . implode(',', BupotTypeEnum::toArray()),
            //     ];
        }

        return [
            // Add your validation rules here
        ];
    }
}
